UPDATE mvapi.dbo.Powiat SET Name = 'bełchatowski' WHERE Code = '100100';
UPDATE mvapi.dbo.Powiat SET Name = 'kutnowski' WHERE Code = '100200';
UPDATE mvapi.dbo.Powiat SET Name = 'łaski' WHERE Code = '100300';
UPDATE mvapi.dbo.Powiat SET Name = 'łęczycki' WHERE Code = '100400';
UPDATE mvapi.dbo.Powiat SET Name = 'łowicki' WHERE Code = '100500';
UPDATE mvapi.dbo.Powiat SET Name = 'łódzki wschodni' WHERE Code = '100600';
UPDATE mvapi.dbo.Powiat SET Name = 'opoczyński' WHERE Code = '100700';
UPDATE mvapi.dbo.Powiat SET Name = 'pabianicki' WHERE Code = '100800';
UPDATE mvapi.dbo.Powiat SET Name = 'pajęczański' WHERE Code = '100900';
UPDATE mvapi.dbo.Powiat SET Name = 'piotrkowski' WHERE Code = '101000';
UPDATE mvapi.dbo.Powiat SET Name = 'poddębicki' WHERE Code = '101100';
UPDATE mvapi.dbo.Powiat SET Name = 'radomszczański' WHERE Code = '101200';
UPDATE mvapi.dbo.Powiat SET Name = 'rawski' WHERE Code = '101300';
UPDATE mvapi.dbo.Powiat SET Name = 'sieradzki' WHERE Code = '101400';
UPDATE mvapi.dbo.Powiat SET Name = 'skierniewicki' WHERE Code = '101500';
UPDATE mvapi.dbo.Powiat SET Name = 'tomaszowski' WHERE Code = '101600';
UPDATE mvapi.dbo.Powiat SET Name = 'wieluński' WHERE Code = '101700';
UPDATE mvapi.dbo.Powiat SET Name = 'wieruszowski' WHERE Code = '101800';
UPDATE mvapi.dbo.Powiat SET Name = 'zduńskowolski' WHERE Code = '101900';
UPDATE mvapi.dbo.Powiat SET Name = 'zgierski' WHERE Code = '102000';
UPDATE mvapi.dbo.Powiat SET Name = 'brzeziński' WHERE Code = '102100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Łódź' WHERE Code = '106100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Piotrków Trybunalski' WHERE Code = '106200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Skierniewice' WHERE Code = '106300';
UPDATE mvapi.dbo.Powiat SET Name = 'bocheński' WHERE Code = '120100';
UPDATE mvapi.dbo.Powiat SET Name = 'brzeski' WHERE Code = '120200';
UPDATE mvapi.dbo.Powiat SET Name = 'chrzanowski' WHERE Code = '120300';
UPDATE mvapi.dbo.Powiat SET Name = 'dąbrowski' WHERE Code = '120400';
UPDATE mvapi.dbo.Powiat SET Name = 'gorlicki' WHERE Code = '120500';
UPDATE mvapi.dbo.Powiat SET Name = 'krakowski' WHERE Code = '120600';
UPDATE mvapi.dbo.Powiat SET Name = 'limanowski' WHERE Code = '120700';
UPDATE mvapi.dbo.Powiat SET Name = 'miechowski' WHERE Code = '120800';
UPDATE mvapi.dbo.Powiat SET Name = 'myślenicki' WHERE Code = '120900';
UPDATE mvapi.dbo.Powiat SET Name = 'nowosądecki' WHERE Code = '121000';
UPDATE mvapi.dbo.Powiat SET Name = 'nowotarski' WHERE Code = '121100';
UPDATE mvapi.dbo.Powiat SET Name = 'olkuski' WHERE Code = '121200';
UPDATE mvapi.dbo.Powiat SET Name = 'oświęcimski' WHERE Code = '121300';
UPDATE mvapi.dbo.Powiat SET Name = 'proszowicki' WHERE Code = '121400';
UPDATE mvapi.dbo.Powiat SET Name = 'suski' WHERE Code = '121500';
UPDATE mvapi.dbo.Powiat SET Name = 'tarnowski' WHERE Code = '121600';
UPDATE mvapi.dbo.Powiat SET Name = 'tatrzański' WHERE Code = '121700';
UPDATE mvapi.dbo.Powiat SET Name = 'wadowicki' WHERE Code = '121800';
UPDATE mvapi.dbo.Powiat SET Name = 'wielicki' WHERE Code = '121900';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Kraków' WHERE Code = '126100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Nowy Sącz' WHERE Code = '126200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Tarnów' WHERE Code = '126300';
UPDATE mvapi.dbo.Powiat SET Name = 'białobrzeski' WHERE Code = '140100';
UPDATE mvapi.dbo.Powiat SET Name = 'ciechanowski' WHERE Code = '140200';
UPDATE mvapi.dbo.Powiat SET Name = 'garwoliński' WHERE Code = '140300';
UPDATE mvapi.dbo.Powiat SET Name = 'gostyniński' WHERE Code = '140400';
UPDATE mvapi.dbo.Powiat SET Name = 'grodziski' WHERE Code = '140500';
UPDATE mvapi.dbo.Powiat SET Name = 'grójecki' WHERE Code = '140600';
UPDATE mvapi.dbo.Powiat SET Name = 'kozienicki' WHERE Code = '140700';
UPDATE mvapi.dbo.Powiat SET Name = 'legionowski' WHERE Code = '140800';
UPDATE mvapi.dbo.Powiat SET Name = 'lipski' WHERE Code = '140900';
UPDATE mvapi.dbo.Powiat SET Name = 'łosicki' WHERE Code = '141000';
UPDATE mvapi.dbo.Powiat SET Name = 'makowski' WHERE Code = '141100';
UPDATE mvapi.dbo.Powiat SET Name = 'miński' WHERE Code = '141200';
UPDATE mvapi.dbo.Powiat SET Name = 'mławski' WHERE Code = '141300';
UPDATE mvapi.dbo.Powiat SET Name = 'nowodworski' WHERE Code = '141400';
UPDATE mvapi.dbo.Powiat SET Name = 'ostrołęcki' WHERE Code = '141500';
UPDATE mvapi.dbo.Powiat SET Name = 'ostrowski' WHERE Code = '141600';
UPDATE mvapi.dbo.Powiat SET Name = 'otwocki' WHERE Code = '141700';
UPDATE mvapi.dbo.Powiat SET Name = 'piaseczyński' WHERE Code = '141800';
UPDATE mvapi.dbo.Powiat SET Name = 'płocki' WHERE Code = '141900';
UPDATE mvapi.dbo.Powiat SET Name = 'płoński' WHERE Code = '142000';
UPDATE mvapi.dbo.Powiat SET Name = 'pruszkowski' WHERE Code = '142100';
UPDATE mvapi.dbo.Powiat SET Name = 'przasnyski' WHERE Code = '142200';
UPDATE mvapi.dbo.Powiat SET Name = 'przysuski' WHERE Code = '142300';
UPDATE mvapi.dbo.Powiat SET Name = 'pułtuski' WHERE Code = '142400';
UPDATE mvapi.dbo.Powiat SET Name = 'radomski' WHERE Code = '142500';
UPDATE mvapi.dbo.Powiat SET Name = 'siedlecki' WHERE Code = '142600';
UPDATE mvapi.dbo.Powiat SET Name = 'sierpecki' WHERE Code = '142700';
UPDATE mvapi.dbo.Powiat SET Name = 'sochaczewski' WHERE Code = '142800';
UPDATE mvapi.dbo.Powiat SET Name = 'sokołowski' WHERE Code = '142900';
UPDATE mvapi.dbo.Powiat SET Name = 'szydłowiecki' WHERE Code = '143000';
UPDATE mvapi.dbo.Powiat SET Name = 'warszawski zachodni' WHERE Code = '143200';
UPDATE mvapi.dbo.Powiat SET Name = 'węgrowski' WHERE Code = '143300';
UPDATE mvapi.dbo.Powiat SET Name = 'wołomiński' WHERE Code = '143400';
UPDATE mvapi.dbo.Powiat SET Name = 'wyszkowski' WHERE Code = '143500';
UPDATE mvapi.dbo.Powiat SET Name = 'zwoleński' WHERE Code = '143600';
UPDATE mvapi.dbo.Powiat SET Name = 'żuromiński' WHERE Code = '143700';
UPDATE mvapi.dbo.Powiat SET Name = 'żyrardowski' WHERE Code = '143800';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Ostrołęka' WHERE Code = '146100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Płock' WHERE Code = '146200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Radom' WHERE Code = '146300';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Siedlce' WHERE Code = '146400';
UPDATE mvapi.dbo.Powiat SET Name = 'Warszawa' WHERE Code = '146501';
UPDATE mvapi.dbo.Powiat SET Name = 'brzeski' WHERE Code = '160100';
UPDATE mvapi.dbo.Powiat SET Name = 'głubczycki' WHERE Code = '160200';
UPDATE mvapi.dbo.Powiat SET Name = 'kędzierzyńsko-kozielski' WHERE Code = '160300';
UPDATE mvapi.dbo.Powiat SET Name = 'kluczborski' WHERE Code = '160400';
UPDATE mvapi.dbo.Powiat SET Name = 'krapkowicki' WHERE Code = '160500';
UPDATE mvapi.dbo.Powiat SET Name = 'namysłowski' WHERE Code = '160600';
UPDATE mvapi.dbo.Powiat SET Name = 'nyski' WHERE Code = '160700';
UPDATE mvapi.dbo.Powiat SET Name = 'oleski' WHERE Code = '160800';
UPDATE mvapi.dbo.Powiat SET Name = 'opolski' WHERE Code = '160900';
UPDATE mvapi.dbo.Powiat SET Name = 'prudnicki' WHERE Code = '161000';
UPDATE mvapi.dbo.Powiat SET Name = 'strzelecki' WHERE Code = '161100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Opole' WHERE Code = '166100';
UPDATE mvapi.dbo.Powiat SET Name = 'bieszczadzki' WHERE Code = '180100';
UPDATE mvapi.dbo.Powiat SET Name = 'brzozowski' WHERE Code = '180200';
UPDATE mvapi.dbo.Powiat SET Name = 'dębicki' WHERE Code = '180300';
UPDATE mvapi.dbo.Powiat SET Name = 'jarosławski' WHERE Code = '180400';
UPDATE mvapi.dbo.Powiat SET Name = 'jasielski' WHERE Code = '180500';
UPDATE mvapi.dbo.Powiat SET Name = 'kolbuszowski' WHERE Code = '180600';
UPDATE mvapi.dbo.Powiat SET Name = 'krośnieński' WHERE Code = '180700';
UPDATE mvapi.dbo.Powiat SET Name = 'leżajski' WHERE Code = '180800';
UPDATE mvapi.dbo.Powiat SET Name = 'lubaczowski' WHERE Code = '180900';
UPDATE mvapi.dbo.Powiat SET Name = 'łańcucki' WHERE Code = '181000';
UPDATE mvapi.dbo.Powiat SET Name = 'mielecki' WHERE Code = '181100';
UPDATE mvapi.dbo.Powiat SET Name = 'niżański' WHERE Code = '181200';
UPDATE mvapi.dbo.Powiat SET Name = 'przemyski' WHERE Code = '181300';
UPDATE mvapi.dbo.Powiat SET Name = 'przeworski' WHERE Code = '181400';
UPDATE mvapi.dbo.Powiat SET Name = 'ropczycko-sędziszowski' WHERE Code = '181500';
UPDATE mvapi.dbo.Powiat SET Name = 'rzeszowski' WHERE Code = '181600';
UPDATE mvapi.dbo.Powiat SET Name = 'sanocki' WHERE Code = '181700';
UPDATE mvapi.dbo.Powiat SET Name = 'stalowowolski' WHERE Code = '181800';
UPDATE mvapi.dbo.Powiat SET Name = 'strzyżowski' WHERE Code = '181900';
UPDATE mvapi.dbo.Powiat SET Name = 'tarnobrzeski' WHERE Code = '182000';
UPDATE mvapi.dbo.Powiat SET Name = 'leski' WHERE Code = '182100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Krosno' WHERE Code = '186100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Przemyśl' WHERE Code = '186200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Rzeszów' WHERE Code = '186300';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Tarnobrzeg' WHERE Code = '186400';
UPDATE mvapi.dbo.Powiat SET Name = 'augustowski' WHERE Code = '200100';
UPDATE mvapi.dbo.Powiat SET Name = 'białostocki' WHERE Code = '200200';
UPDATE mvapi.dbo.Powiat SET Name = 'bielski' WHERE Code = '200300';
UPDATE mvapi.dbo.Powiat SET Name = 'grajewski' WHERE Code = '200400';
UPDATE mvapi.dbo.Powiat SET Name = 'hajnowski' WHERE Code = '200500';
UPDATE mvapi.dbo.Powiat SET Name = 'kolneński' WHERE Code = '200600';
UPDATE mvapi.dbo.Powiat SET Name = 'łomżyński' WHERE Code = '200700';
UPDATE mvapi.dbo.Powiat SET Name = 'moniecki' WHERE Code = '200800';
UPDATE mvapi.dbo.Powiat SET Name = 'sejneński' WHERE Code = '200900';
UPDATE mvapi.dbo.Powiat SET Name = 'bolesławiecki' WHERE Code = '20100';
UPDATE mvapi.dbo.Powiat SET Name = 'siemiatycki' WHERE Code = '201000';
UPDATE mvapi.dbo.Powiat SET Name = 'sokólski' WHERE Code = '201100';
UPDATE mvapi.dbo.Powiat SET Name = 'suwalski' WHERE Code = '201200';
UPDATE mvapi.dbo.Powiat SET Name = 'wysokomazowiecki' WHERE Code = '201300';
UPDATE mvapi.dbo.Powiat SET Name = 'zambrowski' WHERE Code = '201400';
UPDATE mvapi.dbo.Powiat SET Name = 'dzierżoniowski' WHERE Code = '20200';
UPDATE mvapi.dbo.Powiat SET Name = 'głogowski' WHERE Code = '20300';
UPDATE mvapi.dbo.Powiat SET Name = 'górowski' WHERE Code = '20400';
UPDATE mvapi.dbo.Powiat SET Name = 'jaworski' WHERE Code = '20500';
UPDATE mvapi.dbo.Powiat SET Name = 'jeleniogórski' WHERE Code = '20600';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Białystok' WHERE Code = '206100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Łomża' WHERE Code = '206200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Suwałki' WHERE Code = '206300';
UPDATE mvapi.dbo.Powiat SET Name = 'kamiennogórski' WHERE Code = '20700';
UPDATE mvapi.dbo.Powiat SET Name = 'kłodzki' WHERE Code = '20800';
UPDATE mvapi.dbo.Powiat SET Name = 'legnicki' WHERE Code = '20900';
UPDATE mvapi.dbo.Powiat SET Name = 'lubański' WHERE Code = '21000';
UPDATE mvapi.dbo.Powiat SET Name = 'lubiński' WHERE Code = '21100';
UPDATE mvapi.dbo.Powiat SET Name = 'lwówecki' WHERE Code = '21200';
UPDATE mvapi.dbo.Powiat SET Name = 'milicki' WHERE Code = '21300';
UPDATE mvapi.dbo.Powiat SET Name = 'oleśnicki' WHERE Code = '21400';
UPDATE mvapi.dbo.Powiat SET Name = 'oławski' WHERE Code = '21500';
UPDATE mvapi.dbo.Powiat SET Name = 'polkowicki' WHERE Code = '21600';
UPDATE mvapi.dbo.Powiat SET Name = 'strzeliński' WHERE Code = '21700';
UPDATE mvapi.dbo.Powiat SET Name = 'średzki' WHERE Code = '21800';
UPDATE mvapi.dbo.Powiat SET Name = 'świdnicki' WHERE Code = '21900';
UPDATE mvapi.dbo.Powiat SET Name = 'trzebnicki' WHERE Code = '22000';
UPDATE mvapi.dbo.Powiat SET Name = 'bytowski' WHERE Code = '220100';
UPDATE mvapi.dbo.Powiat SET Name = 'chojnicki' WHERE Code = '220200';
UPDATE mvapi.dbo.Powiat SET Name = 'człuchowski' WHERE Code = '220300';
UPDATE mvapi.dbo.Powiat SET Name = 'gdański' WHERE Code = '220400';
UPDATE mvapi.dbo.Powiat SET Name = 'kartuski' WHERE Code = '220500';
UPDATE mvapi.dbo.Powiat SET Name = 'kościerski' WHERE Code = '220600';
UPDATE mvapi.dbo.Powiat SET Name = 'kwidzyński' WHERE Code = '220700';
UPDATE mvapi.dbo.Powiat SET Name = 'lęborski' WHERE Code = '220800';
UPDATE mvapi.dbo.Powiat SET Name = 'malborski' WHERE Code = '220900';
UPDATE mvapi.dbo.Powiat SET Name = 'wałbrzyski' WHERE Code = '22100';
UPDATE mvapi.dbo.Powiat SET Name = 'nowodworski' WHERE Code = '221000';
UPDATE mvapi.dbo.Powiat SET Name = 'pucki' WHERE Code = '221100';
UPDATE mvapi.dbo.Powiat SET Name = 'słupski' WHERE Code = '221200';
UPDATE mvapi.dbo.Powiat SET Name = 'starogardzki' WHERE Code = '221300';
UPDATE mvapi.dbo.Powiat SET Name = 'tczewski' WHERE Code = '221400';
UPDATE mvapi.dbo.Powiat SET Name = 'wejherowski' WHERE Code = '221500';
UPDATE mvapi.dbo.Powiat SET Name = 'sztumski' WHERE Code = '221600';
UPDATE mvapi.dbo.Powiat SET Name = 'wołowski' WHERE Code = '22200';
UPDATE mvapi.dbo.Powiat SET Name = 'wrocławski' WHERE Code = '22300';
UPDATE mvapi.dbo.Powiat SET Name = 'ząbkowicki' WHERE Code = '22400';
UPDATE mvapi.dbo.Powiat SET Name = 'zgorzelecki' WHERE Code = '22500';
UPDATE mvapi.dbo.Powiat SET Name = 'złotoryjski' WHERE Code = '22600';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Gdańsk' WHERE Code = '226100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Gdynia' WHERE Code = '226200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Słupsk' WHERE Code = '226300';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Sopot' WHERE Code = '226400';
UPDATE mvapi.dbo.Powiat SET Name = 'będziński' WHERE Code = '240100';
UPDATE mvapi.dbo.Powiat SET Name = 'bielski' WHERE Code = '240200';
UPDATE mvapi.dbo.Powiat SET Name = 'cieszyński' WHERE Code = '240300';
UPDATE mvapi.dbo.Powiat SET Name = 'częstochowski' WHERE Code = '240400';
UPDATE mvapi.dbo.Powiat SET Name = 'gliwicki' WHERE Code = '240500';
UPDATE mvapi.dbo.Powiat SET Name = 'kłobucki' WHERE Code = '240600';
UPDATE mvapi.dbo.Powiat SET Name = 'lubliniecki' WHERE Code = '240700';
UPDATE mvapi.dbo.Powiat SET Name = 'mikołowski' WHERE Code = '240800';
UPDATE mvapi.dbo.Powiat SET Name = 'myszkowski' WHERE Code = '240900';
UPDATE mvapi.dbo.Powiat SET Name = 'pszczyński' WHERE Code = '241000';
UPDATE mvapi.dbo.Powiat SET Name = 'raciborski' WHERE Code = '241100';
UPDATE mvapi.dbo.Powiat SET Name = 'rybnicki' WHERE Code = '241200';
UPDATE mvapi.dbo.Powiat SET Name = 'tarnogórski' WHERE Code = '241300';
UPDATE mvapi.dbo.Powiat SET Name = 'bieruńsko-lędziński' WHERE Code = '241400';
UPDATE mvapi.dbo.Powiat SET Name = 'wodzisławski' WHERE Code = '241500';
UPDATE mvapi.dbo.Powiat SET Name = 'zawierciański' WHERE Code = '241600';
UPDATE mvapi.dbo.Powiat SET Name = 'żywiecki' WHERE Code = '241700';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Bielsko-Biała' WHERE Code = '246100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Bytom' WHERE Code = '246200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Chorzów' WHERE Code = '246300';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Częstochowa' WHERE Code = '246400';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Dąbrowa Górnicza' WHERE Code = '246500';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Gliwice' WHERE Code = '246600';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Jastrzębie-Zdrój' WHERE Code = '246700';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Jaworzno' WHERE Code = '246800';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Katowice' WHERE Code = '246900';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Mysłowice' WHERE Code = '247000';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Piekary Śląskie' WHERE Code = '247100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Ruda Śląska' WHERE Code = '247200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Rybnik' WHERE Code = '247300';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Siemianowice Śląskie' WHERE Code = '247400';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Sosnowiec' WHERE Code = '247500';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Świętochłowice' WHERE Code = '247600';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Tychy' WHERE Code = '247700';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Zabrze' WHERE Code = '247800';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Żory' WHERE Code = '247900';
UPDATE mvapi.dbo.Powiat SET Name = 'buski' WHERE Code = '260100';
UPDATE mvapi.dbo.Powiat SET Name = 'jędrzejowski' WHERE Code = '260200';
UPDATE mvapi.dbo.Powiat SET Name = 'kazimierski' WHERE Code = '260300';
UPDATE mvapi.dbo.Powiat SET Name = 'kielecki' WHERE Code = '260400';
UPDATE mvapi.dbo.Powiat SET Name = 'konecki' WHERE Code = '260500';
UPDATE mvapi.dbo.Powiat SET Name = 'opatowski' WHERE Code = '260600';
UPDATE mvapi.dbo.Powiat SET Name = 'ostrowiecki' WHERE Code = '260700';
UPDATE mvapi.dbo.Powiat SET Name = 'pińczowski' WHERE Code = '260800';
UPDATE mvapi.dbo.Powiat SET Name = 'sandomierski' WHERE Code = '260900';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Jelenia Góra' WHERE Code = '26100';
UPDATE mvapi.dbo.Powiat SET Name = 'skarżyski' WHERE Code = '261000';
UPDATE mvapi.dbo.Powiat SET Name = 'starachowicki' WHERE Code = '261100';
UPDATE mvapi.dbo.Powiat SET Name = 'staszowski' WHERE Code = '261200';
UPDATE mvapi.dbo.Powiat SET Name = 'włoszczowski' WHERE Code = '261300';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Legnica' WHERE Code = '26200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Wrocław' WHERE Code = '26400';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Wałbrzych' WHERE Code = '26500';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Kielce' WHERE Code = '266100';
UPDATE mvapi.dbo.Powiat SET Name = 'bartoszycki' WHERE Code = '280100';
UPDATE mvapi.dbo.Powiat SET Name = 'braniewski' WHERE Code = '280200';
UPDATE mvapi.dbo.Powiat SET Name = 'działdowski' WHERE Code = '280300';
UPDATE mvapi.dbo.Powiat SET Name = 'elbląski' WHERE Code = '280400';
UPDATE mvapi.dbo.Powiat SET Name = 'ełcki' WHERE Code = '280500';
UPDATE mvapi.dbo.Powiat SET Name = 'giżycki' WHERE Code = '280600';
UPDATE mvapi.dbo.Powiat SET Name = 'iławski' WHERE Code = '280700';
UPDATE mvapi.dbo.Powiat SET Name = 'kętrzyński' WHERE Code = '280800';
UPDATE mvapi.dbo.Powiat SET Name = 'lidzbarski' WHERE Code = '280900';
UPDATE mvapi.dbo.Powiat SET Name = 'mrągowski' WHERE Code = '281000';
UPDATE mvapi.dbo.Powiat SET Name = 'nidzicki' WHERE Code = '281100';
UPDATE mvapi.dbo.Powiat SET Name = 'nowomiejski' WHERE Code = '281200';
UPDATE mvapi.dbo.Powiat SET Name = 'olecki' WHERE Code = '281300';
UPDATE mvapi.dbo.Powiat SET Name = 'olsztyński' WHERE Code = '281400';
UPDATE mvapi.dbo.Powiat SET Name = 'ostródzki' WHERE Code = '281500';
UPDATE mvapi.dbo.Powiat SET Name = 'piski' WHERE Code = '281600';
UPDATE mvapi.dbo.Powiat SET Name = 'szczycieński' WHERE Code = '281700';
UPDATE mvapi.dbo.Powiat SET Name = 'gołdapski' WHERE Code = '281800';
UPDATE mvapi.dbo.Powiat SET Name = 'węgorzewski' WHERE Code = '281900';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Elbląg' WHERE Code = '286100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Olsztyn' WHERE Code = '286200';
UPDATE mvapi.dbo.Powiat SET Name = 'chodzieski' WHERE Code = '300100';
UPDATE mvapi.dbo.Powiat SET Name = 'czarnkowsko-trzcianecki' WHERE Code = '300200';
UPDATE mvapi.dbo.Powiat SET Name = 'gnieźnieński' WHERE Code = '300300';
UPDATE mvapi.dbo.Powiat SET Name = 'gostyński' WHERE Code = '300400';
UPDATE mvapi.dbo.Powiat SET Name = 'grodziski' WHERE Code = '300500';
UPDATE mvapi.dbo.Powiat SET Name = 'jarociński' WHERE Code = '300600';
UPDATE mvapi.dbo.Powiat SET Name = 'kaliski' WHERE Code = '300700';
UPDATE mvapi.dbo.Powiat SET Name = 'kępiński' WHERE Code = '300800';
UPDATE mvapi.dbo.Powiat SET Name = 'kolski' WHERE Code = '300900';
UPDATE mvapi.dbo.Powiat SET Name = 'koniński' WHERE Code = '301000';
UPDATE mvapi.dbo.Powiat SET Name = 'kościański' WHERE Code = '301100';
UPDATE mvapi.dbo.Powiat SET Name = 'krotoszyński' WHERE Code = '301200';
UPDATE mvapi.dbo.Powiat SET Name = 'leszczyński' WHERE Code = '301300';
UPDATE mvapi.dbo.Powiat SET Name = 'międzychodzki' WHERE Code = '301400';
UPDATE mvapi.dbo.Powiat SET Name = 'nowotomyski' WHERE Code = '301500';
UPDATE mvapi.dbo.Powiat SET Name = 'obornicki' WHERE Code = '301600';
UPDATE mvapi.dbo.Powiat SET Name = 'ostrowski' WHERE Code = '301700';
UPDATE mvapi.dbo.Powiat SET Name = 'ostrzeszowski' WHERE Code = '301800';
UPDATE mvapi.dbo.Powiat SET Name = 'pilski' WHERE Code = '301900';
UPDATE mvapi.dbo.Powiat SET Name = 'pleszewski' WHERE Code = '302000';
UPDATE mvapi.dbo.Powiat SET Name = 'poznański' WHERE Code = '302100';
UPDATE mvapi.dbo.Powiat SET Name = 'rawicki' WHERE Code = '302200';
UPDATE mvapi.dbo.Powiat SET Name = 'słupecki' WHERE Code = '302300';
UPDATE mvapi.dbo.Powiat SET Name = 'szamotulski' WHERE Code = '302400';
UPDATE mvapi.dbo.Powiat SET Name = 'średzki' WHERE Code = '302500';
UPDATE mvapi.dbo.Powiat SET Name = 'śremski' WHERE Code = '302600';
UPDATE mvapi.dbo.Powiat SET Name = 'turecki' WHERE Code = '302700';
UPDATE mvapi.dbo.Powiat SET Name = 'wągrowiecki' WHERE Code = '302800';
UPDATE mvapi.dbo.Powiat SET Name = 'wolsztyński' WHERE Code = '302900';
UPDATE mvapi.dbo.Powiat SET Name = 'wrzesiński' WHERE Code = '303000';
UPDATE mvapi.dbo.Powiat SET Name = 'złotowski' WHERE Code = '303100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Kalisz' WHERE Code = '306100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Konin' WHERE Code = '306200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Leszno' WHERE Code = '306300';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Poznań' WHERE Code = '306400';
UPDATE mvapi.dbo.Powiat SET Name = 'białogardzki' WHERE Code = '320100';
UPDATE mvapi.dbo.Powiat SET Name = 'choszczeński' WHERE Code = '320200';
UPDATE mvapi.dbo.Powiat SET Name = 'drawski' WHERE Code = '320300';
UPDATE mvapi.dbo.Powiat SET Name = 'goleniowski' WHERE Code = '320400';
UPDATE mvapi.dbo.Powiat SET Name = 'gryficki' WHERE Code = '320500';
UPDATE mvapi.dbo.Powiat SET Name = 'gryfiński' WHERE Code = '320600';
UPDATE mvapi.dbo.Powiat SET Name = 'kamieński' WHERE Code = '320700';
UPDATE mvapi.dbo.Powiat SET Name = 'kołobrzeski' WHERE Code = '320800';
UPDATE mvapi.dbo.Powiat SET Name = 'koszaliński' WHERE Code = '320900';
UPDATE mvapi.dbo.Powiat SET Name = 'myśliborski' WHERE Code = '321000';
UPDATE mvapi.dbo.Powiat SET Name = 'policki' WHERE Code = '321100';
UPDATE mvapi.dbo.Powiat SET Name = 'pyrzycki' WHERE Code = '321200';
UPDATE mvapi.dbo.Powiat SET Name = 'sławieński' WHERE Code = '321300';
UPDATE mvapi.dbo.Powiat SET Name = 'stargardzki' WHERE Code = '321400';
UPDATE mvapi.dbo.Powiat SET Name = 'szczecinecki' WHERE Code = '321500';
UPDATE mvapi.dbo.Powiat SET Name = 'świdwiński' WHERE Code = '321600';
UPDATE mvapi.dbo.Powiat SET Name = 'wałecki' WHERE Code = '321700';
UPDATE mvapi.dbo.Powiat SET Name = 'łobeski' WHERE Code = '321800';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Koszalin' WHERE Code = '326100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Szczecin' WHERE Code = '326200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Świnoujście' WHERE Code = '326300';
UPDATE mvapi.dbo.Powiat SET Name = 'aleksandrowski' WHERE Code = '40100';
UPDATE mvapi.dbo.Powiat SET Name = 'brodnicki' WHERE Code = '40200';
UPDATE mvapi.dbo.Powiat SET Name = 'bydgoski' WHERE Code = '40300';
UPDATE mvapi.dbo.Powiat SET Name = 'chełmiński' WHERE Code = '40400';
UPDATE mvapi.dbo.Powiat SET Name = 'golubsko-dobrzyński' WHERE Code = '40500';
UPDATE mvapi.dbo.Powiat SET Name = 'grudziądzki' WHERE Code = '40600';
UPDATE mvapi.dbo.Powiat SET Name = 'inowrocławski' WHERE Code = '40700';
UPDATE mvapi.dbo.Powiat SET Name = 'lipnowski' WHERE Code = '40800';
UPDATE mvapi.dbo.Powiat SET Name = 'mogileński' WHERE Code = '40900';
UPDATE mvapi.dbo.Powiat SET Name = 'nakielski' WHERE Code = '41000';
UPDATE mvapi.dbo.Powiat SET Name = 'radziejowski' WHERE Code = '41100';
UPDATE mvapi.dbo.Powiat SET Name = 'rypiński' WHERE Code = '41200';
UPDATE mvapi.dbo.Powiat SET Name = 'sępoleński' WHERE Code = '41300';
UPDATE mvapi.dbo.Powiat SET Name = 'świecki' WHERE Code = '41400';
UPDATE mvapi.dbo.Powiat SET Name = 'toruński' WHERE Code = '41500';
UPDATE mvapi.dbo.Powiat SET Name = 'tucholski' WHERE Code = '41600';
UPDATE mvapi.dbo.Powiat SET Name = 'wąbrzeski' WHERE Code = '41700';
UPDATE mvapi.dbo.Powiat SET Name = 'włocławski' WHERE Code = '41800';
UPDATE mvapi.dbo.Powiat SET Name = 'żniński' WHERE Code = '41900';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Bydgoszcz' WHERE Code = '46100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Grudziądz' WHERE Code = '46200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Toruń' WHERE Code = '46300';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Włocławek' WHERE Code = '46400';
UPDATE mvapi.dbo.Powiat SET Name = 'bialski' WHERE Code = '60100';
UPDATE mvapi.dbo.Powiat SET Name = 'biłgorajski' WHERE Code = '60200';
UPDATE mvapi.dbo.Powiat SET Name = 'chełmski' WHERE Code = '60300';
UPDATE mvapi.dbo.Powiat SET Name = 'hrubieszowski' WHERE Code = '60400';
UPDATE mvapi.dbo.Powiat SET Name = 'janowski' WHERE Code = '60500';
UPDATE mvapi.dbo.Powiat SET Name = 'krasnostawski' WHERE Code = '60600';
UPDATE mvapi.dbo.Powiat SET Name = 'kraśnicki' WHERE Code = '60700';
UPDATE mvapi.dbo.Powiat SET Name = 'lubartowski' WHERE Code = '60800';
UPDATE mvapi.dbo.Powiat SET Name = 'lubelski' WHERE Code = '60900';
UPDATE mvapi.dbo.Powiat SET Name = 'łęczyński' WHERE Code = '61000';
UPDATE mvapi.dbo.Powiat SET Name = 'łukowski' WHERE Code = '61100';
UPDATE mvapi.dbo.Powiat SET Name = 'opolski' WHERE Code = '61200';
UPDATE mvapi.dbo.Powiat SET Name = 'parczewski' WHERE Code = '61300';
UPDATE mvapi.dbo.Powiat SET Name = 'puławski' WHERE Code = '61400';
UPDATE mvapi.dbo.Powiat SET Name = 'radzyński' WHERE Code = '61500';
UPDATE mvapi.dbo.Powiat SET Name = 'rycki' WHERE Code = '61600';
UPDATE mvapi.dbo.Powiat SET Name = 'świdnicki' WHERE Code = '61700';
UPDATE mvapi.dbo.Powiat SET Name = 'tomaszowski' WHERE Code = '61800';
UPDATE mvapi.dbo.Powiat SET Name = 'włodawski' WHERE Code = '61900';
UPDATE mvapi.dbo.Powiat SET Name = 'zamojski' WHERE Code = '62000';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Biała Podlaska' WHERE Code = '66100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Chełm' WHERE Code = '66200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Lublin' WHERE Code = '66300';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Zamość' WHERE Code = '66400';
UPDATE mvapi.dbo.Powiat SET Name = 'gorzowski' WHERE Code = '80100';
UPDATE mvapi.dbo.Powiat SET Name = 'krośnieński' WHERE Code = '80200';
UPDATE mvapi.dbo.Powiat SET Name = 'międzyrzecki' WHERE Code = '80300';
UPDATE mvapi.dbo.Powiat SET Name = 'nowosolski' WHERE Code = '80400';
UPDATE mvapi.dbo.Powiat SET Name = 'słubicki' WHERE Code = '80500';
UPDATE mvapi.dbo.Powiat SET Name = 'strzelecko-drezdenecki' WHERE Code = '80600';
UPDATE mvapi.dbo.Powiat SET Name = 'sulęciński' WHERE Code = '80700';
UPDATE mvapi.dbo.Powiat SET Name = 'świebodziński' WHERE Code = '80800';
UPDATE mvapi.dbo.Powiat SET Name = 'zielonogórski' WHERE Code = '80900';
UPDATE mvapi.dbo.Powiat SET Name = 'żagański' WHERE Code = '81000';
UPDATE mvapi.dbo.Powiat SET Name = 'żarski' WHERE Code = '81100';
UPDATE mvapi.dbo.Powiat SET Name = 'wschowski' WHERE Code = '81200';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Gorzów Wielkopolski' WHERE Code = '86100';
UPDATE mvapi.dbo.Powiat SET Name = 'm. Zielona Góra' WHERE Code = '86200';
